version: '3.8'
services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./docker/php-fpm/php.ini-production:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mongodb
      - redis
      - clickhouse
      - soketi
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - REDIS_HOST=redis
      - PUSHER_HOST=soketi
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - 80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  mongodb:
    image: mongo:latest
    ports:
      - 27017
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:latest
    ports:
      - 6379
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 8123
      - 9000
    volumes:
      - clickhouse_data:/var/lib/clickhouse
  soketi:
    image: quay.io/soketi/soketi:latest
    ports:
      - 6001
    environment:
      - SOKETI_PORT=6001
      - SOKETI_DEFAULT_APP_ID=app-id
      - SOKETI_DEFAULT_APP_KEY=app-key
      - SOKETI_DEFAULT_APP_SECRET=app-secret
volumes:
  mongodb_data:
  clickhouse_data:
