version: '3.8'

services:
    php-fpm:
        build:
            args:
                user: ${USER:-1000}
                uid: ${UID:-1000}
                SUPERVISOR_USER: ${SUPERVISOR_USER:-ns}
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/php-fpm/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/php-fpm/php.ini-production:/usr/local/etc/php/php.ini
            - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
        restart: unless-stopped
        networks:
            - foodhub-network
    nginx:
        image: nginx:1.27.4-alpine3.21
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        networks:
            - foodhub-network
    postgres:
        image: postgres:16.6-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: foodhub
            POSTGRES_USER: foodhub
            POSTGRES_PASSWORD: secret
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
            - foodhub-network
    redis:
        image: redis:7.4.2-alpine
        ports:
            - "6379:6379"
        restart: unless-stopped
        networks:
            - foodhub-network
    clickhouse:
        image: yandex/clickhouse-server:22.1.3.7
        ports:
            - "8123:8123"
            - "9000:9000"
        environment:
            CLICKHOUSE_DB: foodhub_analytics
            CLICKHOUSE_USER: foodhub
            CLICKHOUSE_PASSWORD: secret
        volumes:
            - clickhouse_data:/var/lib/clickhouse
        restart: unless-stopped
        networks:
            - foodhub-network
    soketi:
        image: quay.io/soketi/soketi:1.6.1-16-alpine
        ports:
            - "6001:6001"
        environment:
            SOKETI_PORT: ${SOKETI_PORT:-6001}
            SOKETI_DEFAULT_APP_ID: ${SOKETI_DEFAULT_APP_ID:-foodhub-app}
            SOKETI_DEFAULT_APP_KEY: ${SOKETI_DEFAULT_APP_KEY:-foodhub-key}
            SOKETI_DEFAULT_APP_SECRET: ${SOKETI_DEFAULT_APP_SECRET:-foodhub-secret}
            SOKETI_DEBUG: "true"
        restart: unless-stopped
        networks:
            - foodhub-network

volumes:
    postgres_data:
    clickhouse_data:
networks:
    foodhub-network:
        driver: bridge
