services:
    php-fpm:
        build:
            args:
                user: ${USER:-1000}
                uid: ${UID:-1000}
                SUPERVISOR_USER: ${SUPERVISOR_USER:-ns}  # Подтягиваем из .env
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        working_dir: /var/www/html
#        environment:
#            - SUPERVISOR_USER=${SUPERVISOR_USER:-ns}  # Подтягиваем из .env
#            - SUPERVISOR_USER=${SUPERVISOR_USER:-www-data}  # если PROD/DEV-TEST
        volumes:
            - .:/var/www/html
            - ./docker/php-fpm/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/php-fpm/php.ini-production:/usr/local/etc/php/php.ini
            - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on:
            - mongodb
            - redis
            - clickhouse
            - soketi
        restart: unless-stopped
    nginx:
        image: nginx:1.27.4-alpine3.21
        ports:
            - 80
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        restart: unless-stopped
    mongodb:
        image: mongo:8.0.6
        ports:
            - 27017
        volumes:
            - mongodb_data:/data/db
        restart: unless-stopped
    redis:
        image: redis:7.4.2
        ports:
            - 6379
        restart: unless-stopped
    clickhouse:
        image: yandex/clickhouse-server:22.1.3.7
        ports:
            - 8123
            - 9000
        volumes:
            - clickhouse_data:/var/lib/clickhouse
        restart: unless-stopped
    soketi:
        image: quay.io/soketi/soketi:1.6.1-16-alpine
#        image: quay.io/soketi/soketi:pr-1295-16-alpine
        ports:
            - 6001
        environment:
            - SOKETI_PORT=6001
            - SOKETI_DEFAULT_APP_ID=app-id
            - SOKETI_DEFAULT_APP_KEY=app-key
            - SOKETI_DEFAULT_APP_SECRET=app-secret
        restart: unless-stopped
volumes:
    mongodb_data:
    clickhouse_data:
